[package]
name = "nzskkserv-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = {git = "https://github.com/emilk/egui", package="eframe"}
tray-item = "0.7"

[build-dependencies]
windres = "0.2"
