[package]
name = "nzskkserv-gui"
version = "0.1.4"
edition = "2021"

[dependencies]
eframe = { git = "https://github.com/emilk/egui", package = "eframe" }
egui = "0.22"
tray-item = "0.8"
tokio = { version = "1", features = ["full"] }
nzskkserv-core = { path = "../nzskkserv-core", version = "0.1" }
anyhow = "1"
directories = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.7"
encoding_rs = "0.8"
sanitize-filename = "0.4"
reqwest = "0.11"
once_cell = "1"
crossbeam = "0.8"
auto-launch = "0.4"

[build-dependencies]
windres = "0.2"
