[package]
name = "nzskkserv-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { git = "https://github.com/emilk/egui", package = "eframe" }
egui = "0.18"
tray-item = "0.7"
tokio = { version = "1", features = ["full"] }
nzskkserv-core = { path = "../nzskkserv-core", version = "0.1" }
simple_logger = { version = "2.1" }
anyhow = "1"
directories = "4"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
encoding_rs = "0.8"
sanitize-filename = "0.4"
reqwest = "0.11"
once_cell = "1"
poll-promise = { version = "0.1", features = ["tokio"] }
crossbeam = "0.8"

[build-dependencies]
windres = "0.2"
