[application]

# App (Project) Name
name = "nzskkserv"

[bundle]
identifier = "dev.nazo6.nzskkserv"
publisher = "nazo6"

[web.app]

# HTML title tag content
title = "nzskkserv"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
