[workspace]
members = ["nzskkserv-core", "nzskkserv-gui"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.43.0" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
