[config]
unstable_features = ["CTRL_C_HANDLING"]
default_to_workspace = false
skip_core_tasks = true

[tasks.dev]
run_task = { name = ["dev-dx", "dev-tw"], parallel = true }

[tasks.dev-dx]
script = '''
cd nzskkserv-gui && dx serve
'''

[tasks.dev-tw]
script = '''
cd nzskkserv-gui && npx @tailwindcss/cli -i ./input.css -o ./assets/tailwind.css --watch
'''

[tasks.build]
script = '''
cd nzskkserv-gui && npx @tailwindcss/cli -i ./input.css -o ./assets/tailwind.css && dx build --release
'''
