[package]
name = "nzskkserv-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3"
tokio = { version = "1", features = ["full"] }
nzskkserv-core = { path = "../nzskkserv-core" }
simple_logger = { version = "2.1" }
log = "0.4"
