[package]
name = "nzskkserv-core"
version = "0.1.0"
edition = "2018"

[dependencies]
nzskkserv-server = { path = "../nzskkserv-server" }
tokio = { version = "1", features = ["fs", "sync"] }
thiserror = "1"
directories = "4"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
log = "0.4"
sanitize-filename = "0.3"
encoding_rs = "0.8"
