[package]
name = "nzskkserv-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["net", "rt", "io-util"] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = "0.1"
anyhow = "1"
bytes = "1"
